---
title: "RIT Psych"
subtitle: "Department of Psychology, Rochester Institute of Technology"
author: "Dustin Haraden, PhD"
---

# Overview

Here we can have some overview

## Description

What is it that this website is all about?

## Faculty

Maybe include a list of faculty here?

-   Links to lab websites and faculty info

-   Maybe overall research interests and lab projects

## Page Options - Things that are common across the department

-   Using git/github

-   SONA

-   Zotero

-   Sourcing measures

    -   Identifying databases and how to identify "correct" measures

-   Secondary Data analysis

    -   Databases (task an RA to search)

    -   Separate them out by domains (as well as identifying the level of access)

        -   LDBase - <https://ldbase.org/>
        -   NHANES
        -   Data Hoarders subreddit

-   Citi Trainings

    -   Clarify which CITI trainings are needed

-   Qualtrics

    -   Templates

    -   Building up a library of questionnaires

    -   Other Resources (slideshow)

        -   Randomization

        -   Question Type

        -   Settings to navigate

        -   UserX

        -   Targeting for different audiences

        -   Embedded Data

            -   Linking surveys together with included data

        -   Naming conventions for items

        -   Recoding variables

        -   Simulate Participants

        -   Individualized Links

            -   Email vs. CSV

-   Other types of data collection (Connect by CloudResearch, MTurk, Prolific)

-   COLA Student Fund, SURF, CSTEP, McNair

-   IRB

    -   Document sent from Joe

    -   HRSO Example Consent Form

-   Using your computer

    -   File structure

    -   Naming Conventions

    -   Using Excel/Google Sheets

    -   Adobe Suite

-   General Professional Development

    -   Letters of Rec - Best practices for asking/selecting

        -   Provide info around how much time they work will reflect the type of letters that they can write

        -   Recommendations of timelines to set themselves up for good letters and other things

    -   CV Construction

    -   Writing personal statements

        -   Grad applications - kisses of death

        -   Purdue Owl on personal statements

-   Research Templates

    -   Poster Presentations
        -   How to print a poster!

-   Using PowerPoint/Canva for presentations

-   Statistical Softwares/Experiment Running Software

    -   R

    -   jamovi

    -   SPSS

    -   python/psychopy

    -   superlab

    -   Prolific/cloud-connect

    -   gorilla

## Groupings

### Overview of doing your study

-   Getting the Data

    -   Data Management

-   Analyzing the Data

-   Presenting/Sharing the Data

### Professional Development

-   Letters of Rec - Best practices for asking/selecting

    -   Provide info around how much time they work will reflect the type of letters that they can write

    -   Recommendations of timelines to set themselves up for good letters and other things

-   CV Construction

-   Writing personal statements

    -   Grad applications - kisses of death

    -   Purdue Owl on personal statements

-   Website?? Think about it, but understand what goes into it
